### PR TITLE
NameError: undefined local variable or method `rest' for #<IronWorker::APIClient:0x005646ec018d60> 1 File "/mnt/task/bundle/ruby/2.2.0/gems/iron_worker-3.3.0/lib/iron_worker/api_client.rb"

### PR DESCRIPTION
**Pull request by cdimartino**
This line began throwing an error after moving to 3.3.0.  We've reverted to our branch and commented out this line.  Not sure what caused it to suddenly trigger the bug, perhaps Net::HTTP::Persistent became defined.  Either way, __rest__ is not defined in that scope.

### CODE REVIEW

**Comment by lightcap** [comment]
I don't know if this is the right fix for this problem, but since it's a log entry, it probably doesn't really matter. Any chance we could get this merged and released?

**Comment by lightcap** [comment]
Actually, I'm still getting the same error message when using devbootcamp/iron_worker_ruby@f13d62c. @cdimartino I assume you've gotten past with with the line commented out?

**Comment by cdimartino** [comment]
we have gotten past it with that line commented out - yes.

**Comment by treeder** [comment]
#47 looks like the better option here.

**Pull request closed without merging**
