### PR TITLE
Add task bulk create. 

### PR DESCRIPTION
**Pull request by sunloverz**

### CODE REVIEW

**Comment by sunloverz** [comment]
Added @Stephenitis 's PR https://github.com/iron-io/iron_worker_ruby_ng/pull/211
assigning @treeder @Stephenitis

**Comment by sunloverz** [comment]
@treeder maybe its better to remove old iron_worker_ruby_ng cli methods `codes_patch`, `codes_create`, `codes_create_async`?

**Comment by sunloverz** [comment]
or make them more usable?

**Comment by treeder** [comment]
Well, we can't drop the old cli support just yet until dockerworker stuff is out of beta, and even then we'll have to deprecate ng cli and give it time to phase out.

**Pull request merged**
